### ISSUE TITLE
Gitter badge link is incorrect

### ISSUE THREAD

**Issue by kreczko** [scientific-python/cookie#112]
Current link is
```
https://gitter.im/{{cookiecutter.url}}/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
```

which leads to entries like
```
https://gitter.im/https://github.com/<account or org>/<project name>/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
```

Instead, it should probably be `{{cookiecutter.url}}` &rarr; `{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}`:

```
https://gitter.im/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}//community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
```

Does anyone know if `cookiecutter.github_username` also works for organizations? If yes, I can make a PR.

**Comment by henryiii** [comment]
Oops! Yes, `cookiecutter.github_username` should work for orgs (it is very much supposed to work if set to `scikit-hep`, which is an org!)
