### ISSUE TITLE
cibuildwheel pypy on os x does not like numpy

### ISSUE THREAD

**Issue by nsmith-** [scientific-python/cookie#15]
I ran into https://github.com/joerick/cibuildwheel/issues/402 while building wheels that now incorporate numpy
See e.g. https://github.com/cms-nanoAOD/correctionlib/runs/2521360719?check_suite_focus=true#step:3:1003
Seems the current best solution is to drop pypy wheels for os x?

**Comment by henryiii** [comment]
FYI,

```bash
brew install openblas
OPENBLAS="$(brew --prefix openblas)" cibuildwheel ...
```

was listed as a solution. The "best" solution would be for NumPy to provide macOS PyPy wheels. Though, of course, if you use pybind11, you don't need them when building, and you can disable testing for just this one job with TEST_SKIP.

**Comment by henryiii** [comment]
Assuming the situation is a bit better (more wheels provided by numpy for pypy these days)
