### ISSUE TITLE
Ruff `target-version` can be automatically inferred if `requires-python` is set

### ISSUE THREAD

**Issue by burgholzer** [scientific-python/cookie#201]
According to https://beta.ruff.rs/docs/settings/#target-version, the `target-version` property used for ruff can be inferred from the `project.requires-python` field, if it is present.
Repo-review currently requires the `target-version` to be set in 
https://github.com/scientific-python/cookie/blob/884ef327f322ce1dcd23f803ad622b73cbb8fe34/src/sp_repo_review/checks/ruff.py#L35-L50

Based on the above, this check could be relaxed a little. Maybe to something like:
```python
class RF002(Ruff):
    "Target version must be set"
    requires = {"RF001"}

    @staticmethod
    def check(pyproject: dict[str, Any]) -> bool:
        """
        Must select a minimum version to target. Affects pyupgrade,
        isort, and others. Can be inferred from project.requires-python.
        """

        match pyproject:
            case {"tool": {"ruff": {"target-version": str()}}}:
                return True
            case {"project": {"requires-python": str()}}:
                return True
            case _:
                return False
```
Or even something where it is suggested to not specify `tool.ruff.target-version` whenever `project.requires-python` is specified.

**Comment by henryiii** [comment]
This sounds great. I’d go with allowing either for now, as you have above, and later we could make having both disallowed.

**Comment by henryiii** [comment]
(I suspect this might be somewhat new. Also wondering how it handles more complex version boudaries)

**Comment by burgholzer** [comment]
> This sounds great. I’d go with allowing either for now, as you have above, and later we could make having both disallowed.

Do you want me to submit a corresponding PR?

> (I suspect this might be somewhat new. Also wondering how it handles more complex version boudaries)

The feature was requested in https://github.com/astral-sh/ruff/issues/2039 and implemented in https://github.com/astral-sh/ruff/pull/3470 on March 13, which went into `ruff` `v0.0.255` (https://github.com/astral-sh/ruff/releases/tag/v0.0.255). astral-sh/ruff#2039 has some details on the handling of version ranges (mostly refers to how `black` handles this as of version 23.1.0).

**Comment by henryiii** [comment]
Sure, please do.

**Comment by henryiii** [comment]
(FYI, this check was added in repo-review 0.5, https://github.com/scientific-python/repo-review/releases/tag/v0.5.0 - in February, which explains why it didn't have this :) )
