### ISSUE TITLE
Allow for black mirror in pre-commit check

### ISSUE THREAD

**Issue by WilliamJamieson** [scientific-python/cookie#254]
Note that the latest `black` [docs](https://black.readthedocs.io/en/latest/integrations/source_version_control.html#version-control-integration) now recommends that users use `https://github.com/psf/black-pre-commit-mirror` instead of `https://github.com/psf/black` because the version of `black` provided by the mirror is faster.

The mirror supports all `black` tags from `22.3.0` to through to the current `23.7.0` tag. Hence, I think the guide should start recommending using this version of the `black` repo, or at the very least the `sp-repo-review` tool should allow for the use of this URL.

**Comment by henryiii** [comment]
Also made the following PRs:

- scikit-hep/pyBumpHunter#18
- scikit-hep/resample#178
- scikit-hep/cabinetry#426
- scikit-hep/iminuit#925
- scikit-hep/boost-histogram#872
- scikit-hep/mplhep#438
- scikit-hep/vector#367
- scikit-hep/uproot-browser#152
- scikit-hep/pyhepmc#68
- scikit-hep/hepstats#120
- scikit-hep/fastjet#242
- scikit-hep/hist#523
- scikit-hep/scikit-hep-testdata#128
- scikit-hep/histoprint#122
- scikit-hep/uproot5#929
- scikit-hep/decaylanguage#362
- scikit-hep/mplhep_data#41
- scikit-hep/awkward#2633
- scikit-hep/particle#520
- scikit-hep/hepunits#145
- scikit-hep/pyhf#2270
- scikit-hep/pylhe#211
- pybind/pybind11#4787
- pybind/python_example#170
- pybind/scikit_build_example#105
- pybind/cmake_example#
- scikit-build/scikit-build#1021
- scikit-build/scikit-build-core#456
- scikit-build/scikit-build-sample-projects#42
- pypa/wheel#555
- pypa/cibuildwheel#1569
- pypa/build#652
