### ISSUE TITLE
Review the PyGrep hooks suggestion

### ISSUE THREAD

**Issue by WilliamJamieson** [scientific-python/cookie#258]
The PyGrep hooks ([PC170](https://learn.scientific-python.org/development/guides/style/#PC170)) may now be partially replaced by `ruff`. In particular the [`PGH`](https://beta.ruff.rs/docs/rules/#pygrep-hooks-pgh) rule set appears to cover many of the checks suggested in PC170. In particular, `ruff` can cover the "python" related checks.

**Comment by henryiii** [comment]
There's a note just below "Note that if you are using Ruff, you don’t need the python-* hooks above.". Though we probably should prioritize the ruff-compatible version.
