### ISSUE TITLE
Don't flag ruff select rules when ALL is enabled

### ISSUE THREAD

**Issue by WilliamJamieson** [scientific-python/cookie#283]
Ruff has the option of setting `select = ["ALL"]`, which selects all the rule sets not in "[preview](https://learn.scientific-python.org/development/guides/style/#ruff)". In particular, this includes

- flake8-bugbear (RF101)
- isort (RF102)
- pyupgrade (RF103).

However, repo review flags these as failures when `"ALL"` is set even though they are actually being used.

**Comment by henryiii** [comment]
That’s supposed to work, actually: https://github.com/scientific-python/cookie/blob/64b1bfbfdecfe0f9bf9032915c4489e74ebfea06/src/sp_repo_review/checks/ruff.py#L106

**Comment by henryiii** [comment]
Ahh, that was in #273, maybe it’s not in a release.

**Comment by WilliamJamieson** [comment]
You are right it's not in the current release. Thanks for already having this implemented. Feel free to close this issue now or when the next release occurs.

**Comment by henryiii** [comment]
Next release will be out soon. :)

**Comment by henryiii** [comment]
(Tagged, should go up to PyPI soon)
