### ISSUE TITLE
Ruff select ALL regression

### ISSUE THREAD

**Issue by WilliamJamieson** [scientific-python/cookie#311]
It appears that the issue reported in #283 has re-appeared in the latest version: `2023.10.27`, while it was fixed in the previous version: `2023.09.21`.

See astropy/astropy#15367, if one changes the cookie's pre-commit version from `2023.09.21` to `2023.10.27` reproduces this error.

**Comment by henryiii** [comment]
It's because we started picking up `ruff.toml`/`.ruff.toml`, and don't support the extend option yet.

**Comment by henryiii** [comment]
(Working on it today)
