### ISSUE TITLE
Question - importing test utilities?

### ISSUE THREAD

**Issue by jack-mcivor** [scientific-python/cookie#318]
Do you have any recommendations for handling the cases where I want some code importable only in tests? One example in open source is https://github.com/pydantic/pydantic/blob/main/tests/test_datetime.py#L20

I think this would require including a `tests/__init__.py` file? I noticed that you recommended against that here https://github.com/scientific-python/cookie/blob/e88cb440a1e24dd51633a71f2a8c33ac4d4c459c/docs/pages/guides/pytest.md?plain=1#L112-L114 , so interested in your thoughts.

**Comment by henryiii** [comment]
I believe the recommendation is, for pytest 7+, to use [pythonpath](https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-pythonpath). You can make a utils directory in your test folder, then add `pythonpath="tests/utils"` to your `pyproject.toml`. That works regardless of the import mode you are using in pytest.
