### ISSUE TITLE
Packaging tutorial: Directory structure unclear

### ISSUE THREAD

**Issue by gunnarvoet** [scientific-python/cookie#340]
The guide puts `__init__.py` and `refraction.py` directly into `src/`
https://github.com/scientific-python/cookie/blob/7250955345ad4ba4a3c3341c9895c9758b82bb41/docs/pages/tutorials/packaging.md?plain=1#L53-L58

whereas the directory structure listing has `src/example/...`
https://github.com/scientific-python/cookie/blob/7250955345ad4ba4a3c3341c9895c9758b82bb41/docs/pages/tutorials/packaging.md?plain=1#L90-L95

**Comment by henryiii** [comment]
Oops, that’s a mistake. `__init__.py` should never be directly in `src`.
