### ISSUE TITLE
Typo in Packaging tutorial

### ISSUE THREAD

**Issue by edsq** [scientific-python/cookie#344]
Thanks for this nice collection of wisdom!

In the Packaging tutorial [here](https://learn.scientific-python.org/development/tutorials/packaging/#create-a-minimal-installable-python-package), the `__init__.py` and `refraction.py` files are placed in the wrong directory, under `src` instead of `src/example`.  The `tree` output of the file structure is correct, however.

**Comment by henryiii** [comment]
Also found in #340. No one has fixed it yet, I can soon. The GitHub Actions artifact v4 major changes has been eating up time.

**Comment by edsq** [comment]
Woops, sorry for the duplicate.
