### ISSUE TITLE
RF002: You have both Ruff's target-version and project.requires-python. You only need the later.

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [scientific-python/cookie#407]
No, the lat(t)er is (currently) not (always) enough!

If the repo contains a `ruff.toml` or `.ruff.toml` file, ruff will not read `pyproject.toml`. So even though `requires-python` may be set in `pyproject.toml`, you still need to set `target-version` in `ruff.toml` or `.ruff.toml`.

Perhaps that's a ruff bug, but it's still under discussion in an open issue: https://github.com/astral-sh/ruff/issues/10299

I noticed this in https://github.com/sphinx-doc/sphinx/pull/12250

**Comment by henryiii** [comment]
Ahh, interesting. I don't usually use those unless I don't have a pyproject.toml. The check should be fixed.
