### ISSUE TITLE
Right way to attribute derivative work

### ISSUE THREAD

**Issue by phinate** [scientific-python/cookie#421]
Hi @henryiii! I'm developing a [differently configured template](https://github.com/alan-turing-institute/python-project-template) that uses a lot of the functionality present in this template, but targets a much less broad set of users (mostly just the research community adjacent to my institute). Partly an educational + convenience project for me, and partly to have freedom to customise deeply.

There's some re-wiring to use things with `copier` only, but some of the pipelines are directly pulled from this codebase. I've inherited the BSD-3 license, and have made multiple references to this repo in our README, with no direct mention of you or other contributors names as per the license. Just double checking that this is your preferred way of attribution?

Thanks for all your work on this template :)

**Comment by henryiii** [comment]
I think that sounds fine!

**Comment by phinate** [comment]
Perfect, thanks :)
