### ISSUE TITLE
GHA no longer has permissions to make PRs?

### ISSUE THREAD

**Issue by henryiii** [scientific-python/cookie#443]
> Choose whether GitHub Actions can create pull requests or submit approving pull request reviews.

This is now disabled and greyed out, and the bump workflow is broken. @jarrodmillman or @stefanv, do you know what changed?

**Comment by jarrodmillman** [comment]
It should be fixed now. We recent got an enterpise account and I had to enable it there. I wasn't expecting the upgrade to automatically disable things. But it looks like it did. There may be other things it changed, so we will need to keep an eye out.
