### ISSUE TITLE
Allow alternative to codespell in sp-repo-review

### ISSUE THREAD

**Issue by burgholzer** [scientific-python/cookie#459]
`PC160` currently suggests the use of `codespell` in pre-commit.
However, codespell can be quite slow at times and can easily miss certain typos.
While looking for alternatives, I stumbled upon the [crate-ci/typos](https://github.com/crate-ci/typos) repository that is also used by [ruff](https://github.com/astral-sh/ruff/blob/0b4d3ce39bccaa6e4fd65f265e58d952e097f552/.pre-commit-config.yaml#L45-L48) in favor of codespell.
The tool has quite an easy config scheme, is drastically faster, and also provides auto-fix support. Furthermore, it caught at least some additional typos that were not spotted by codespell when we introduced the new tool for our framework (https://github.com/cda-tum/mqt-core/pull/625).

Right now, the use of the `crate-ci/typos` in favor of `codespell` requires us to ignore `"PC160"`.

Would it make sense to expand the scope of the rule a little bit to something like "Uses a spellchecker" and allow for codespell and/or `crate-ci/typos` to be used?

**Comment by henryiii** [comment]
Codespell does support auto-fixes.

> Would it make sense to expand the scope of the rule a little bit to something like "Uses a spellchecker" and allow for codespell and/or crate-ci/typos to be used?

Absolutely. We already do this with black/ruff, flake8/ruff, nox/tox/hatch/spin, etc.

**Comment by burgholzer** [comment]
> Codespell does support auto-fixes.

👍🏼 

> > Would it make sense to expand the scope of the rule a little bit to something like "Uses a spellchecker" and allow for codespell and/or crate-ci/typos to be used?
> 
> Absolutely. We already do this with black/ruff, flake8/ruff, nox/tox/hatch/spin, etc.

I am not too familiar with the repo-review part of this project. However, I could try to submit a corresponding PR based on how this is handled for the other combinations of tools.
Or would you rather work on this yourself?

**Comment by henryiii** [comment]
Well, I would have said PR, but I see a bit of cleanup I could do on the base class. It's at https://github.com/scientific-python/cookie/blob/2f1d453930e3dca006c948c7db5969119f3465e1/src/sp_repo_review/checks/precommit.py#L48-L64. Let me check.
