### ISSUE TITLE
PC111 blacken-docs can be disable if we use docstring formatting in ruff

### ISSUE THREAD

**Issue by tkoyama010** [scientific-python/cookie#464]
Thanks for great project. I notice one thing in cheking :)

ruff-format has [Docstring formatting](https://docs.astral.sh/ruff/formatter/#docstring-formatting). So we can disable [PC111 blacken-docs](https://learn.scientific-python.org/development/guides/style/#format) if we use that.

Thanks for your attention.

**Comment by henryiii** [comment]
Duplicate of https://github.com/scientific-python/cookie/issues/343.  Ruff is supposed to check `*.md` and `*.rst` files someday, but until it does, this is not a replacement.

**Comment by tkoyama010** [comment]
Thank you. Sorry for Duplication.
