### ISSUE TITLE
Add `.copier-answers.yml` to generated `.gitignore`

### ISSUE THREAD

**Issue by lucascolley** [scientific-python/cookie#470]
I just made a new project with Copier. `prettier` immediately failed in CI because the value of the `project_short_description` field in `.copier-answers.yml` did not start on a new line.

I think this file should just be ignored by git, right?

**Comment by henryiii** [comment]
I think it should be ignored by linters. I think you might want it in git if you use it to update the project via copier's update feature.

**Comment by henryiii** [comment]
Does pre-commit respect generated files attributes in `.gitattributes`?

**Comment by lucascolley** [comment]
thanks for the fix!
