### ISSUE TITLE
GH200: Dependabot configuration file extension

### ISSUE THREAD

**Issue by angelo-peronio** [scientific-python/cookie#485]
The [repository](https://github.com/angelo-peronio/gsffile) of the gssfile library [fails](https://learn.scientific-python.org/development/guides/repo-review/?repo=angelo-peronio%2Fgsffile&branch=master) the GH200 rule "Maintained by Dependabot" because the Dependabot config file is named `dependabot.yaml`, whereas repo-review expects only `dependabot.yml`.

Can it be made so that repo-review is satisfied with both `.yaml` and `.yml` extensions?

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by henryiii** [comment]
If it works with both, yes.

**Comment by henryiii** [comment]
I’m not seeing any mention of the .yaml being supported here: https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide

**Comment by angelo-peronio** [comment]
Thank you for looking into this. I was able to run it [successfully](https://github.com/angelo-peronio/gsffile/actions/runs/10722349317/job/29733061290) right now.

**Comment by angelo-peronio** [comment]
Thank you very much!
